# An Informal Introduction to Python
[The [source material](https://docs.python.org/3.5/tutorial/introduction.html) for the first part is from Python 3.5.1, but the contents of this tutorial should apply to almost any version of Python 3. For the second part the source material was obtained from [here](http://cs231n.github.io/python-numpy-tutorial/)

Many of the examples in this manual, even those entered at the interactive prompt, include comments. Comments in Python start with the hash character, `#`, and extend to the end of the physical line. A comment may appear at the start of a line or following whitespace or code, but not within a string literal. A hash character within a string literal is just a hash character. Since comments are to clarify code and are not interpreted by Python, they may be omitted when typing in examples.

Some examples:

In [1]:
# This is the first comment
spam = 1  # and this is the second comment
          # ... and now a third!
text = "# This is not a comment because it's inside quotes."

## Using Python as a Calculator
Let's try some simple Python commands.

### Numbers
The interpreter acts as a simple calculator: you can type an expression at it and it will write the value. Expression syntax is straightforward: the operators `+`, `-`, `*` and `/` work just like in most other languages (for example, Pascal or C); parentheses (`()`) can be used for grouping. For example:

In [2]:
2 + 2

4

In [3]:
50 - 5*6

20

In [4]:
(50 - 5*6) / 4

5.0

In [5]:
8 / 5  # Division always returns a floating point number.

1.6

The integer numbers (e.g. `2`, `4`, `20`) have type [`int`](https://docs.python.org/3.5/library/functions.html#int), the ones with a fractional part (e.g. `5.0`, `1.6`) have type [`float`](https://docs.python.org/3.5/library/functions.html#float). We will see more about numeric types later in the tutorial.

Division (`/`) always returns a float. To do [floor division](https://docs.python.org/3.5/glossary.html#term-floor-division) and get an integer result (discarding any fractional result) you can use the `//` operator; to calculate the remainder you can use `%`:

In [6]:
17 / 3  # Classic division returns a float.

5.666666666666667

In [7]:
17 // 3  # Floor division discards the fractional part.

5

In [8]:
17 % 3  # The % operator returns the remainder of the division.

2

In [9]:
5 * 3 + 2  # result * divisor + remainder

17

With Python, it is possible to use the `**` operator to calculate powers:

In [10]:
5 ** 2  # 5 squared

25

In [11]:
2 ** 7  # 2 to the power of 7

128

Do note that `**` has higher precedence than `-`, so if you want a negative base you will need parentheses:

In [12]:
-3**2  # Same as -(3**2)

-9

In [13]:
(-3)**2

9

The equal sign (`=`) is used to assign a value to a variable. Afterwards, no result is displayed before the next interactive prompt:

In [14]:
width = 20
height = 5 * 9
width * height

900

If a variable is not defined (assigned a value), trying to use it will give you an error:

In [15]:
n  # Try to access an undefined variable.

NameError: name 'n' is not defined

There is full support for floating point; operators with mixed type operands convert the integer operand to floating point:

In [16]:
3 * 3.75 / 1.5

7.5

In [17]:
7.0 / 2

3.5

In interactive mode, the last printed expression is assigned to the variable `_`. This means that when you are using Python as a desk calculator, it is somewhat easier to continue calculations, for example:

In [18]:
tax = 12.5 / 100
price = 100.50
price * tax

12.5625

In [19]:
price + _

113.0625

In [20]:
round(_, 2)

113.06

This variable should be treated as read-only by the user. Don't explicitly assign a value to it, you would create an independent local variable with the same name masking the built-in variable with its magic behavior.

In addition to `int` and `float`, Python supports other types of numbers, such as [`Decimal`](https://docs.python.org/3.5/library/decimal.html#decimal.Decimal) and [`Fraction`](https://docs.python.org/3.5/library/fractions.html#fractions.Fraction). Python also has built-in support for [complex numbers](https://docs.python.org/3.5/library/stdtypes.html#typesnumeric), and uses the `j` or `J` suffix to indicate the imaginary part (e.g. `3+5j`).

### Strings

Besides numbers, Python can also manipulate strings, which can be expressed in several ways. They can be enclosed in single quotes (`'...'`) or double quotes (`"..."`) with the same result. `\` can be used to escape quotes:

In [21]:
'spam eggs'  # Single quotes.

'spam eggs'

In [22]:
'doesn\'t'  # Use \' to escape the single quote...

"doesn't"

In [23]:
"doesn't"  # ...or use double quotes instead.

"doesn't"

In [24]:
'"Yes," he said.'

'"Yes," he said.'

In [25]:
"\"Yes,\" he said."

'"Yes," he said.'

In [26]:
'"Isn\'t," she said.'

'"Isn\'t," she said.'

In the interactive interpreter, the output string is enclosed in quotes and special characters are escaped with backslashes. While this might sometimes look different from the input (the enclosing quotes could change), the two strings are equivalent. The string is enclosed in double quotes if the string contains a single quote and no double quotes, otherwise it is enclosed in single quotes. The [`print()`](https://docs.python.org/3.5/library/functions.html#print) function produces a more readable output, by omitting the enclosing quotes and by printing escaped and special characters:

In [27]:
'"Isn\'t," she said.'

'"Isn\'t," she said.'

In [28]:
print('"Isn\'t," she said.')

"Isn't," she said.


In [29]:
s = 'First line.\nSecond line.'  # \n means newline.
s  # Without print(), \n is included in the output.

'First line.\nSecond line.'

In [30]:
print(s)  # With print(), \n produces a new line.

First line.
Second line.


If you don't want characters prefaced by `\` to be interpreted as special characters, you can use _raw strings_ by adding an `r` before the first quote:

In [31]:
print('C:\some\name')  # Here \n means newline!

C:\some
ame


In [32]:
print(r'C:\some\name')  # Note the r before the quote.

C:\some\name


String literals can span multiple lines. One way is using triple-quotes: `"""..."""` or `'''...'''`. End of lines are automatically included in the string, but it's possible to prevent this by adding a `\` at the end of the line. The following example:

In [33]:
print("""\
Usage: thingy [OPTIONS]
     -h                        Display this usage message
     -H hostname               Hostname to connect to
""")

Usage: thingy [OPTIONS]
     -h                        Display this usage message
     -H hostname               Hostname to connect to



Strings can be concatenated (glued together) with the `+` operator, and repeated with `*`:

In [34]:
# 3 times 'un', followed by 'ium'
3 * 'un' + 'ium'

'unununium'

Two or more _string literals_ (i.e. the ones enclosed between quotes) next to each other are automatically concatenated.

In [35]:
'Py' 'thon'

'Python'

This only works with two literals though, not with variables or expressions:

In [36]:
prefix = 'Py'
prefix 'thon'  # Can't concatenate a variable and a string literal.

SyntaxError: invalid syntax (<ipython-input-36-00ad70cd97bc>, line 2)

In [37]:
('un' * 3) 'ium'

SyntaxError: invalid syntax (<ipython-input-37-f4764cbe42a8>, line 1)

If you want to concatenate variables or a variable and a literal, use `+`:

In [38]:
prefix = 'Py'
prefix + 'thon'

'Python'

This feature is particularly useful when you want to break long strings:

In [39]:
text = ('Put several strings within parentheses '
            'to have them joined together.')
text

'Put several strings within parentheses to have them joined together.'

Strings can be _indexed_ (subscripted), with the first character having index 0. There is no separate character type; a character is simply a string of size one:

In [40]:
word = 'Python'
word[0]  # Character in position 0.

'P'

In [41]:
word[5]  # Character in position 5.

'n'

Indices may also be negative numbers, to start counting from the right:

In [42]:
word[-1]  # Last character.

'n'

In [43]:
word[-2]  # Second-last character.

'o'

In [44]:
word[-6]

'P'

Note that since -0 is the same as 0, negative indices start from -1.

In addition to indexing, _slicing_ is also supported. While indexing is used to obtain individual characters, slicing allows you to obtain substring:

In [45]:
word[0:2]  # Characters from position 0 (included) to 2 (excluded).

'Py'

In [46]:
word[2:5]  # Characters from position 2 (included) to 5 (excluded).

'tho'

Note how the start is always included, and the end always excluded. This makes sure that `s[:i] + s[i:]` is always equal to `s`:

In [47]:
word[:2] + word[2:]

'Python'

In [48]:
word[:4] + word[4:]

'Python'

Slice indices have useful defaults; an omitted first index defaults to zero, an omitted second index defaults to the size of the string being sliced.

In [49]:
word[:2]  # Character from the beginning to position 2 (excluded).

'Py'

In [50]:
word[4:]  # Characters from position 4 (included) to the end.

'on'

In [51]:
word[-2:] # Characters from the second-last (included) to the end.

'on'

One way to remember how slices work is to think of the indices as pointing between characters, with the left edge of the first character numbered 0. Then the right edge of the last character of a string of _n_ characters has index _n_, for example:

The first row of numbers gives the position of the indices 0...6 in the string; the second row gives the corresponding negative indices. The slice from _i_ to _j_ consists of all characters between the edges labeled _i_ and _j_, respectively.

For non-negative indices, the length of a slice is the difference of the indices, if both are within bounds. For example, the length of `word[1:3]` is 2.

Attempting to use an index that is too large will result in an error:

In [52]:
word[42]  # The word only has 6 characters.

IndexError: string index out of range

In [53]:
word[4:42]

'on'

In [54]:
word[42:]

''

Python strings cannot be changed, they are [immutable](https://docs.python.org/3.5/glossary.html#term-immutable). Therefore, assigning to an indexed position in the string results in an error:

In [55]:
word[0] = 'J'

TypeError: 'str' object does not support item assignment

In [56]:
word[2:] = 'py'

TypeError: 'str' object does not support item assignment

In [57]:
'J' + word[1:]

'Jython'

In [58]:
word[:2] + 'Py'

'PyPy'

The built-in function [`len()`](https://docs.python.org/3.5/library/functions.html#len) returns the length of a string:

In [59]:
s = 'supercalifragilisticexpialidocious'
len(s)

34

See also:

- [Text Sequence Type str](https://docs.python.org/3.5/library/stdtypes.html#textseq): Strings are examples of _sequence types_, and support the common operations supported by such types.
- [String Methods](https://docs.python.org/3.5/library/stdtypes.html#string-methods): Strings support a large number of methods for basic transformations and searching.
- [Format String Syntax](https://docs.python.org/3.5/library/string.html#formatstrings): Information about string formatting with [`str.format()`](https://docs.python.org/3.5/library/string.html#formatstrings).
- [`printf`-style String Formatting](https://docs.python.org/3.5/library/stdtypes.html#old-string-formatting): The old formatting operations invoked when strings and Unicode strings are the left operand of the `%` operator.

### Lists

Python knows a number of _compound_ data types, used to group together other values. The most versatile is the [_list_](https://docs.python.org/3.5/library/stdtypes.html#typesseq-list), which can be written as a list of comma-separated values (items) between square brackets. Lists might contain items of different types, but usually the items all have the same type.

In [60]:
squares = [1, 4, 9, 16, 25]
squares

[1, 4, 9, 16, 25]

Like strings (and all other built-in [sequence](https://docs.python.org/3.5/glossary.html#term-sequence) type), lists can be indexed and sliced:

In [61]:
squares[0]  # Indexing returns the item.

1

In [62]:
squares[-1]

25

In [63]:
squares[-3:]  # Slicing returns a new list.

[9, 16, 25]

All slice operations return a new list containing the requested elements. This means that the following slice returns a new (shallow) copy of the list:

In [64]:
squares[:]

[1, 4, 9, 16, 25]

Lists also support operations like concatenation:

In [65]:
squares + [36, 49, 64, 81, 100]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

Unlike strings, which are [immutable](https://docs.python.org/3.5/glossary.html#term-immutable), lists are a [mutable](https://docs.python.org/3.5/glossary.html#term-mutable) type, i.e. it is possible to change their content:

In [66]:
cubes = [1, 8, 27, 65, 125]  # Something's wrong here ...
4 ** 3  # the cube of 4 is 64, not 65!

64

In [67]:
cubes[3] = 64  # Replace the wrong value.
cubes

[1, 8, 27, 64, 125]

You can also add new items at the end of the list, by using the `append()` method (we will see more about methods later):

In [68]:
cubes.append(216)  # Add the cube of 6 ...
cubes.append(7 ** 3)  # and the cube of 7.
cubes

[1, 8, 27, 64, 125, 216, 343]

Assignment to slices is also possible, and this can even change the size of the list or clear it entirely:

In [69]:
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
letters

['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [70]:
# Replace some values.
letters[2:5] = ['C', 'D', 'E']
letters

['a', 'b', 'C', 'D', 'E', 'f', 'g']

In [71]:
# Now remove them.
letters[2:5] = []
letters

['a', 'b', 'f', 'g']

In [72]:
# Clear the list by replacing all the elements with an empty list.
letters[:] = []
letters

[]

The built-in function [`len()`](https://docs.python.org/3.5/library/functions.html#len) also applies to lists:

In [73]:
letters = ['a', 'b', 'c', 'd']
len(letters)

4

It is possible to nest lists (create lists containing other lists), for example:

In [74]:
a = ['a', 'b', 'c']
n = [1, 2, 3]
x = [a, n]
x

[['a', 'b', 'c'], [1, 2, 3]]

In [75]:
x[0]

['a', 'b', 'c']

In [76]:
x[0][1]

'b'

## Loops
You can use a for loop to iterate through each element in a list:

In [77]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

cat
dog
monkey


Use enumerate if you want the index of each element:

In [78]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))

#1: cat
#2: dog
#3: monkey


### List comprehension

This tool can be use to simplificate loops in which we operate each element in a list:

In [79]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
squares

[0, 1, 4, 9, 16]

In [80]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
squares

[0, 1, 4, 9, 16]

You can even add conditions:

In [81]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
even_squares

[0, 4, 16]

Or use it to initialize a list with some values:

In [82]:
nonempty_list = [0 for x in range(0, 10)]
nonempty_list

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

## Dictionaries
A dictionary stores (key, value) pairs, similar to a **Map** in Java. You can use it like this:

In [83]:
d = {'cat': 'cute', 'dog': 'furry'}
d['cat']

'cute'

Check if a dictionary has a given key:

In [84]:
'cat' in d

True

You can also modify values in a dictionary:

In [85]:
d['fish'] = 'wet'
d['fish']

'wet'

If a dictionary doesn't contains a key, Python will throw an error:

In [86]:
d['monkey']

KeyError: 'monkey'

Use get if you want to use a dictionary with keys that may not be inside it:

In [87]:
d.get('monkey', 'N/A')

'N/A'

In [88]:
d.get('fish', 'N/A')

'wet'

You can also delete keys like this:

In [89]:
del d['fish']
d.get('fish', 'N/A')

'N/A'

### Dictionary loops

In [90]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs))

A cat has 4 legs
A spider has 8 legs
A person has 2 legs


In [91]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print('A %s has %d legs' % (animal, legs))

A cat has 4 legs
A spider has 8 legs
A person has 2 legs


### Dictionary comprehension

In [92]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
even_num_to_square

{0: 0, 2: 4, 4: 16}

## Sets

In [93]:
animals = {'cat', 'dog'}
len(animals)

2

In [94]:
animals.add('cat') 
len(animals)

2

### Set comprehension

In [95]:
from math import sqrt
nums = {int(sqrt(x)) for x in range(30)}
nums

{0, 1, 2, 3, 4, 5}

## Tuples

In [96]:
t = (1, 2, 3)
t

(1, 2, 3)

In [97]:
t.append(4)

AttributeError: 'tuple' object has no attribute 'append'

In [98]:
d = {(x, x + 1): x for x in range(10)}
d

{(0, 1): 0,
 (1, 2): 1,
 (2, 3): 2,
 (3, 4): 3,
 (4, 5): 4,
 (5, 6): 5,
 (6, 7): 6,
 (7, 8): 7,
 (8, 9): 8,
 (9, 10): 9}

## Functions

In [99]:
def hello(name, loud=False):
    if loud:
        print('HELLO, %s!' % name.upper())
    else:
        print('Hello, %s' % name)

In [100]:
hello('Bob')

Hello, Bob


In [101]:
hello('Fred', loud=True)

HELLO, FRED!


# Numpy

In [102]:
import numpy as np

a = np.array([1, 2, 3])
type(a)

numpy.ndarray

In [103]:
a.shape

(3,)

In [104]:
a[0], a[1], a[2]

(1, 2, 3)

In [105]:
a[0] = 5
a

array([5, 2, 3])

In [106]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)                     

(2, 3)


In [107]:
b[0, 0], b[0, 1], b[1, 0]

(1, 2, 4)

## Other ways to create arrays

In [108]:
a = np.zeros((2,2)) 
a

array([[0., 0.],
       [0., 0.]])

In [109]:
b = np.ones((1,2))
b

array([[1., 1.]])

In [110]:
c = np.full((2,2), 7)
c

array([[7, 7],
       [7, 7]])

In [111]:
d = np.eye(2)   
d

array([[1., 0.],
       [0., 1.]])

In [112]:
e = np.random.random((2,2))
e

array([[0.48652082, 0.51914944],
       [0.59769971, 0.31705541]])

In [113]:
np.arange(5)

array([0, 1, 2, 3, 4])

## Slicing

In [114]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [115]:
b = a[:2, 1:3]
b

array([[2, 3],
       [6, 7]])

In [116]:
b[0, 0] = 77 
a

array([[ 1, 77,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Avoiding lower rank slicing

In [117]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [118]:
row_r1 = a[1, :] 
row_r1, row_r1.shape

(array([5, 6, 7, 8]), (4,))

In [119]:
row_r2 = a[1:2, :]
row_r2, row_r2.shape

(array([[5, 6, 7, 8]]), (1, 4))

In [120]:
col_r1 = a[:, 1]
col_r1, col_r1.shape

(array([ 2,  6, 10]), (3,))

In [121]:
col_r2 = a[:, 1:2]
col_r2, col_r2.shape

(array([[ 2],
        [ 6],
        [10]]), (3, 1))

## Indexing

In [122]:
a = np.array([[1,2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [123]:
a[[0, 1, 2], [0, 1, 0]]

array([1, 4, 5])

In [124]:
np.array([a[0, 0], a[1, 1], a[2, 0]])

array([1, 4, 5])

## Boolean array index

In [125]:
a = np.array([[1,2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [126]:
bool_idx = (a > 2) 
bool_idx

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [127]:
a[a > 2]

array([3, 4, 5, 6])

## Operations

### Elementwise operations

In [128]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [129]:
x + y

array([[ 6,  8],
       [10, 12]])

In [130]:
np.add(x, y)

array([[ 6,  8],
       [10, 12]])

In [131]:
x - y

array([[-4, -4],
       [-4, -4]])

In [132]:
np.subtract(x, y)

array([[-4, -4],
       [-4, -4]])

In [133]:
x * y

array([[ 5, 12],
       [21, 32]])

In [134]:
np.multiply(x, y)

array([[ 5, 12],
       [21, 32]])

In [135]:
x / y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [136]:
np.divide(x, y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [137]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

### Matrix multiplication

In [138]:
v = np.array([9,10])
w = np.array([11, 12])

In [139]:
v.dot(w)

219

In [140]:
np.dot(v, w)

219

In [141]:
v @ w

219

### Transpose

In [142]:
x = np.array([[1,2], [3,4]])
x

array([[1, 2],
       [3, 4]])

In [143]:
x.T

array([[1, 3],
       [2, 4]])

In [144]:
v = np.array([1,2,3])
v

array([1, 2, 3])

In [145]:
v.T

array([1, 2, 3])

## Broadcasting

In [146]:
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
v

array([1, 2, 3])

In [147]:
np.reshape(v, (1, 3))

array([[1, 2, 3]])

In [148]:
np.reshape(v, (3, 1)) * w

array([[ 4,  5],
       [ 8, 10],
       [12, 15]])

In [149]:
x = np.array([[1,2,3], [4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [150]:
x+v

array([[2, 4, 6],
       [5, 7, 9]])